### ISSUE TITLE
ایراد ریلیتی در کانفیگ کلش و برطرف کردن آن

### ISSUE THREAD

**Issue by randomguy-on-internet** [hiddify/Hiddify-Server#720]
@hiddify1 
برای اینکه کانفیگ کلش متا ( هیدیفای دسکتاپ) کار کنه باید اینارو اضافه کنید:
```
tls: true
reality-opts:
    public-key: پابلیک کی شما
client-fingerprint: chrome
```
کانیفگ کامل:
```yaml
- name: "reality_grpc_direct_vless 443 4"
  type: vless
  server: دامنه شما
  port: 443
  alpn:
  - h2
  uuid: db7ba30e-5163-407e-qweq-14c5555a7e57
  servername: itunes.apple.com
  tls: true
  udp: true
  network: grpc
  reality-opts:
    public-key: پابلیک کی شما
  grpc-opts:
    grpc-service-name: "ASDFGWSfddsfsdfwert"
  client-fingerprint: chrome
```
